name: CounterSuperSimple
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '3.3.3'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  path_provider: ^2.0.8
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  windows: true
  image_path: "assets/icon.png"