name: Flutter iOS Build (Fakesign)
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Verify Flutter Installation
        run: flutter doctor

      - name: Check for Podfile
        run: |
          if [ ! -f ios/Podfile ]; then
            echo "No Podfile found. Initializing Podfile..."
            flutter create .
          fi

      - name: Install CocoaPods
        run: pod install --project-directory=ios || true

      - name: Build iOS Application (Unsigned IPA)
        run: flutter build ipa --release --no-codesign

      - name: List Build Directory
        run: ls build/ios/ipa/

      # Upload the unsigned IPA file as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-unsigned-build
          path: build/ios/ipa/
