name: iOS Build
on: [push, pull_request]

jobs:
  build:
    name: Build and upload counter.
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-12'
            version: '14.2'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Flutter Build 
        run: flutter build ios --release --no-codesign

      - name: Get version
        id: version
        run: echo "version=$(grep MARKETING_VERSION Build.xcconfig | sed -e "s/MARKETING_VERSION = //g")" >> $GITHUB_OUTPUT

      - name: Echo version
        run: echo "${{ steps.version.outputs.version }}"
        
      - name: Install dependencies
        run: brew install ldid
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Convert to IPA
        run: make ipa

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%c')" >> $GITHUB_OUTPUT

      - name: Get current date in AltStore date form
        id: date_altstore
        run: echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload to new stable release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref_name }}
          draft: true
          files: Counter.ipa
          body: |
            ## Changelog
            
            - TODO
            
            ## Build Info
            
            Built at (UTC): `${{ steps.date.outputs.date }}`
            Built at (UTC date): `${{ steps.date_altstore.outputs.date }}`
            Commit SHA: `${{ github.sha }}`
            Version: `${{ steps.version.outputs.version }}`

      - name: Add version to IPA file name
        run: mv Counter.ipa Counter-${{ steps.version.outputs.version }}.ipa

      - name: Upload Counter.ipa Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Counter-${{ steps.version.outputs.version }}.ipa
          path: Counter-${{ steps.version.outputs.version }}.ipa

      - name: Upload *.dSYM Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Counter-${{ steps.version.outputs.version }}-dSYM
          path: ./*.dSYM/
