name: macOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build macOS Application
        run: flutter build macos --release

      - name: Create DMG
        run: |
          APP_PATH="build/macos/Build/Products/Release/Counter.app"
          DMG_PATH="build/macos/Build/Products/Release/Counter.dmg"
          hdiutil create -volname "Counter" -srcfolder "$APP_PATH" -ov -format UDZO "$DMG_PATH"

      - name: List Build Directory
        run: ls -la build/macos/Build/Products/Release/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/Counter.dmg