name: Flutter action
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: stable
        flutter-version: '2.5.3'

    - name: Verify Flutter version
      run: flutter --version
