name: Flutter action
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.3.3'

    - name: Verify Flutter version
      run: flutter --version

    - name: Build Windows
      run: flutter build windows --release
