name: Flutter Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Linux is generally used for cross-platform Flutter builds

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Verify Flutter Installation
        run: flutter doctor

      # Windows Build Section
      - name: Build Windows Application
        run: flutter build windows --release

      - name: List Windows Build Directory
        run: dir build/windows/x64/runner/Release/

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

      # Android Build Section
      - name: Set Up Android Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk  # Install Java
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
          unzip android-sdk.zip -d $HOME/android-sdk-linux
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk-linux" >> $
