name: Flutter Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # We use Ubuntu for cross-platform builds
    services:
      android-emulator:  # Setting up an Android emulator for testing or environment setup
        image: 'reactivecircus/android-emulator:30.0.26'
        ports:
          - 5554:5554
          - 5555:5555
        options: >-
          --publish 5554:5554
          --publish 5555:5555
          --privileged
        volumes:
          - /dev/kvm:/dev/kvm

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Verify Flutter Installation
        run: flutter doctor

      # Windows Build Section
      - name: Build Windows Application
        run: flutter build windows --release

      - name: List Windows Build Directory
        run: dir build/windows/x64/runner/Release/

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

      # Android Build Section
      - name: Set Up Android SDK
        uses: android-actions/setup-android-sdk@v2  # This sets up the Android SDK
        with:
          java-version: '11'
          package-type: 'platform-tools,build-tools;30.0.3,platforms;android-30'

      - name: Build Android Application
        run: flutter build apk --release

      - name: Upload Android Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/app-release.apk  # Path to the built APK
