name: Flutter Build with Cache
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache Flutter
        uses: actions/cache@v3
        with:
          path: ${{ steps.flutter-action.outputs.CACHE-PATH }}
          key: ${{ runner.os }}-flutter-${{ steps.flutter-action.outputs.CACHE-KEY }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable

      - name: Cache Dart packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}
          key: ${{ runner.os }}-pub-${{ steps.flutter-action.outputs.PUB-CACHE-KEY }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Verify Flutter Installation
        run: flutter doctor

      - name: Build Windows Application
        run: flutter build windows --release

      - name: List Build Directory
        run: dir build/windows/runner/Release/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/
